/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Interfaz.java
 *
 * Created on 23/12/2009, 03:42:44 PM
 */

package Triangulo;

import java.awt.Color;

/**
 *
 * @author Stivenson
 */
public class Interfaz extends javax.swing.JFrame {

    /** Creates new form Interfaz */
    public Interfaz() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Lado1 = new javax.swing.JTextField();
        Lado2 = new javax.swing.JTextField();
        Lado3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Ttriangulo = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        TR = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Hipotenusa = new javax.swing.JTextField();
        Copuesto = new javax.swing.JTextField();
        Cadyacente = new javax.swing.JTextField();
        Aalfa = new javax.swing.JTextField();
        Ateta = new javax.swing.JTextField();
        Seno = new javax.swing.JTextField();
        Coseno = new javax.swing.JTextField();
        Cotangente = new javax.swing.JTextField();
        Tangente = new javax.swing.JTextField();
        Secante = new javax.swing.JTextField();
        Cosecante = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Aviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Lado 1: ");

        jLabel2.setText("Lado 2: ");

        jLabel3.setText("Lado 3: ");

        jLabel4.setText("Tipo de triangulo: ");

        Ttriangulo.setEditable(false);
        Ttriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtrianguloActionPerformed(evt);
            }
        });

        ok.setText("Evaluar");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        TR.setBackground(java.awt.Color.lightGray);
        TR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setText("Si es trangulo rectangulo:");

        jLabel7.setText("Hipotenusa:");

        jLabel8.setText("Cateto Opuesto:");

        jLabel9.setText("Cateto Adyacente:");

        jLabel10.setText("Ángulo Alfa:");

        jLabel11.setText("Ángulo Teta:");

        jLabel12.setText("Seno:");

        jLabel13.setText("Coseno:");

        jLabel14.setText("Tangente:");

        jLabel15.setText("Secante:");

        jLabel16.setText("Cosecante:");

        jLabel17.setText("Cotangente:");

        Hipotenusa.setEditable(false);

        Copuesto.setEditable(false);

        Cadyacente.setEditable(false);

        Aalfa.setEditable(false);

        Ateta.setEditable(false);

        Seno.setEditable(false);

        Coseno.setEditable(false);

        Cotangente.setEditable(false);

        Tangente.setEditable(false);

        Secante.setEditable(false);

        Cosecante.setEditable(false);

        jLabel18.setFont(new java.awt.Font("Ron Maiden", 0, 11));
        jLabel18.setText("De Stívenson Rincón Mora");

        jLabel19.setText("(Alfa)");

        org.jdesktop.layout.GroupLayout TRLayout = new org.jdesktop.layout.GroupLayout(TR);
        TR.setLayout(TRLayout);
        TRLayout.setHorizontalGroup(
            TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, TRLayout.createSequentialGroup()
                .addContainerGap()
                .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel7)
                    .add(TRLayout.createSequentialGroup()
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel9)
                            .add(jLabel8)
                            .add(jLabel10)
                            .add(jLabel11))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, Copuesto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, Cadyacente, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .add(Aalfa, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .add(Ateta, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, Hipotenusa, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)))
                    .add(jLabel6)
                    .add(jLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(TRLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel13)
                            .add(jLabel12)
                            .add(jLabel14)
                            .add(jLabel15)
                            .add(jLabel17)
                            .add(jLabel16))
                        .add(29, 29, 29)
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(Cotangente, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .add(Coseno, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .add(Tangente, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, Secante, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, Cosecante, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, Seno, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                    .add(TRLayout.createSequentialGroup()
                        .add(73, 73, 73)
                        .add(jLabel19)))
                .addContainerGap())
        );
        TRLayout.setVerticalGroup(
            TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(TRLayout.createSequentialGroup()
                .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(TRLayout.createSequentialGroup()
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(Hipotenusa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel8)
                            .add(Copuesto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(Cadyacente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel10)
                            .add(Aalfa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(Ateta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel11))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel18, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                    .add(TRLayout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(jLabel19)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel12)
                            .add(Seno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel13)
                            .add(Coseno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel14)
                            .add(Tangente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel15)
                            .add(Secante, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel16)
                            .add(Cosecante, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(TRLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(Cotangente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel17))))
                .addContainerGap())
        );

        Aviso.setBackground(new java.awt.Color(0, 239, 205));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel1)
                                .add(18, 18, 18)
                                .add(Lado1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel2)
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(Lado3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .add(ok, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .add(Lado2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                            .add(jLabel3))
                        .add(24, 24, 24)
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(Aviso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(Ttriangulo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(TR, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Lado1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Lado2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Lado3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(ok))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .add(Ttriangulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(Aviso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(60, 60, 60)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(TR, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        Aviso.setText( " ");
        TR.setBackground(Color.LIGHT_GRAY);
        setLimpiar();
        Operaciones objeto= new Operaciones(Double.parseDouble(Lado1.getText()),Double.parseDouble(Lado2.getText()),Double.parseDouble(Lado3.getText()));
       
        Ttriangulo.setText(objeto.getTipo());
        if(Ttriangulo.getText().equals("Equilatero")==false){

         Hipotenusa.setText(String.valueOf(objeto.gethipotenusa()));
         Copuesto.setText(String.valueOf(objeto.getCatetoOpuesto()));
         Cadyacente.setText(String.valueOf(objeto.getCatetoAdyacente()));
         Aalfa.setText(String.valueOf(objeto.getAnguloAlfa()));
         Ateta.setText(String.valueOf(objeto.getAnguloTeta()));
         Seno.setText(String.valueOf(objeto.getSeno()));
         Coseno.setText(String.valueOf(objeto.getCoseno()));
         Tangente.setText(String.valueOf(objeto.getTangente()));
         Secante.setText(String.valueOf(objeto.getSecante()));
         Cosecante.setText(String.valueOf(objeto.getCosecante()));
         Cotangente.setText(String.valueOf(objeto.getCotangente()));
        }
        else{
          Aviso.setText( " No es Triángulo Rectangulo ");
          TR.setBackground(Color.gray);
            }
       


       
       
    }//GEN-LAST:event_okActionPerformed

    private void TtrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtrianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TtrianguloActionPerformed
 public void setLimpiar(){
          Hipotenusa.setText("");
           Copuesto.setText("");
         Cadyacente.setText("");
         Aalfa.setText("");
         Ateta.setText("");
         Seno.setText("");
         Coseno.setText("");
         Tangente.setText("");
         Secante.setText("");
         Cosecante.setText("");
         Cotangente.setText("");
      }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Aalfa;
    private javax.swing.JTextField Ateta;
    private javax.swing.JLabel Aviso;
    private javax.swing.JTextField Cadyacente;
    private javax.swing.JTextField Copuesto;
    private javax.swing.JTextField Cosecante;
    private javax.swing.JTextField Coseno;
    private javax.swing.JTextField Cotangente;
    private javax.swing.JTextField Hipotenusa;
    private javax.swing.JTextField Lado1;
    private javax.swing.JTextField Lado2;
    private javax.swing.JTextField Lado3;
    private javax.swing.JTextField Secante;
    private javax.swing.JTextField Seno;
    private javax.swing.JPanel TR;
    private javax.swing.JTextField Tangente;
    private javax.swing.JTextField Ttriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables

}
