/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Interfaz.java
 *
 * Created on 15/12/2009, 07:48:20 PM
 */

package caracteristicas_letra;

/**
 *
 * @author Stivenson
 */
public class Interfaz extends javax.swing.JFrame {

    /** Creates new form Interfaz */
    public Interfaz() {
        initComponents();
    }


/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Csilabas = new javax.swing.JTextArea();
        Ccaracteres = new javax.swing.JTextField();
        Cespacios = new javax.swing.JTextField();
        Cconsonantes = new javax.swing.JTextField();
        Cvocales = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CTsilabas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Tfrase = new javax.swing.JTextField();
        limpiar = new javax.swing.JButton();
        Amayusculas = new javax.swing.JButton();
        Aminusculas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CARACTERISTICAS FRASE");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Stamp Act", 1, 8));
        jLabel2.setText("escriba frase o palabra");

        jLabel1.setFont(new java.awt.Font("Stamp Act", 1, 8));
        jLabel1.setText("Cantidad Caracteres: ");

        jLabel3.setFont(new java.awt.Font("Stamp Act", 1, 8));
        jLabel3.setText("Cantidad Espaciados:");

        jLabel4.setFont(new java.awt.Font("Stamp Act", 1, 8));
        jLabel4.setText("Cantidad Consonantes:");

        jLabel5.setFont(new java.awt.Font("Stamp Act", 1, 8));
        jLabel5.setText("Cantidad de vocales:");

        jLabel6.setFont(new java.awt.Font("Stamp Act", 1, 8));
        jLabel6.setText("Cantidad de silabas:");

        Csilabas.setColumns(20);
        Csilabas.setEditable(false);
        Csilabas.setRows(5);
        jScrollPane1.setViewportView(Csilabas);

        Ccaracteres.setEditable(false);

        Cespacios.setEditable(false);

        Cconsonantes.setEditable(false);

        Cvocales.setEditable(false);

        ok.setText("Evaluar");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ron Maiden", 2, 18));
        jLabel7.setText("De stivenson Rincón Móra");

        jLabel8.setText("( Recuerde las tildes )");

        CTsilabas.setEditable(false);
        CTsilabas.setForeground(new java.awt.Color(51, 0, 51));
        CTsilabas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTsilabasActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Stamp Act", 1, 8));
        jLabel9.setText("sílabas Separadas:");

        limpiar.setText("Límpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        Amayusculas.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Amayusculas.setText("Pasar a mayúsculas");
        Amayusculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmayusculasActionPerformed(evt);
            }
        });

        Aminusculas.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Aminusculas.setText("Pasar a minúsculas");
        Aminusculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AminusculasActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(166, 166, 166)
                .add(jLabel8)
                .addContainerGap(160, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(Tfrase, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 412, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(389, 389, 389))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel6))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(Ccaracteres)
                            .add(Cvocales)
                            .add(CTsilabas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .add(Cconsonantes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .add(Cespacios))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel9)
                                .add(20, 20, 20)))
                        .add(212, 212, 212))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(ok)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(limpiar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Amayusculas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Aminusculas)
                        .addContainerGap())
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addContainerGap(479, Short.MAX_VALUE))))
            .add(jPanel1Layout.createSequentialGroup()
                .add(142, 142, 142)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(329, 329, 329))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(6, 6, 6)
                        .add(jLabel8)
                        .add(11, 11, 11)
                        .add(Tfrase, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(33, 33, 33)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(53, 53, 53)
                                .add(jLabel9)
                                .add(18, 18, 18)
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(43, 43, 43)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(Ccaracteres, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(Cespacios, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(Cconsonantes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(Cvocales, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(CTsilabas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(18, 18, 18)
                        .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(111, 111, 111)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(ok)
                            .add(limpiar)
                            .add(Amayusculas)
                            .add(Aminusculas))))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 430, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        Ccaracteres.setText("");
        Cconsonantes.setText("");
        Cespacios.setText("");
        Cvocales.setText("");
        CTsilabas.setText("");
        Csilabas.setText("");
         
       String frase=Tfrase.getText();
       frase=frase.toLowerCase();
       frase=frase.trim();
      
        
         
        
	 int i;
	 int espacios=0;
	 for(i=0;i<frase.length();i++){
	 	if(frase.charAt(i)==' ')
	 	espacios++;
	 }
	 Ccaracteres.setText(String.valueOf(frase.length()));
         Cespacios.setText(String.valueOf(espacios));
	 int vocales=0,consonantes=0;
         String SacarSilabas= frase;
         SacarSilabas = SacarSilabas + ' '+' ';
         char fraseA[]=SacarSilabas.toCharArray();
	 for(i=0;i<frase.length();i++){

	 	if(frase.charAt(i)!=' '){
	 	if(Seleccion_Silabas.CoOvocal(SacarSilabas.charAt(i),fraseA)=='V')
	 	vocales++;
	 	else
	 	consonantes++;
	 	}

	 }

	 Cvocales.setText(String.valueOf(vocales));
	 Cconsonantes.setText(String.valueOf(consonantes));

	 StringBuffer fraseSB=new StringBuffer(frase);
	 fraseSB.append(" ");
	 char[] fraseM;
         String AcumulaSilabas="";
	 do{
	 String palabra=fraseSB.substring(0,fraseSB.indexOf(" "));
	 AcumulaSilabas=AcumulaSilabas+String.valueOf(Seleccion_Silabas.Silabas(palabra));
	 fraseSB.delete(0,fraseSB.indexOf(" ")+1);
	 }while(fraseSB.length()>1);
         int CAsilabas=0;
      
          for(i=0;i<AcumulaSilabas.length();i++){
              if(AcumulaSilabas.charAt(i)=='-')
                 CAsilabas++;
          }
          String silabasfinales=AcumulaSilabas.substring(0,AcumulaSilabas.length()-1);
	  Csilabas.setText(silabasfinales);
          CTsilabas.setText(String.valueOf(CAsilabas));
         
    }//GEN-LAST:event_okActionPerformed

    private void CTsilabasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTsilabasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CTsilabasActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
       Ccaracteres.setText("");
        Cconsonantes.setText("");
        Cespacios.setText("");
        Cvocales.setText("");
        CTsilabas.setText("");
        Csilabas.setText("");
        Tfrase.setText("");


    }//GEN-LAST:event_limpiarActionPerformed

    private void AminusculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AminusculasActionPerformed
    String AMI=Tfrase.getText();
   AMI=AMI.toLowerCase();
   Tfrase.setText(AMI);
    }//GEN-LAST:event_AminusculasActionPerformed

    private void AmayusculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmayusculasActionPerformed
    String AMA=Tfrase.getText();
    AMA=AMA.toUpperCase();
    Tfrase.setText(AMA);
    }//GEN-LAST:event_AmayusculasActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Amayusculas;
    private javax.swing.JButton Aminusculas;
    private javax.swing.JTextField CTsilabas;
    private javax.swing.JTextField Ccaracteres;
    private javax.swing.JTextField Cconsonantes;
    private javax.swing.JTextField Cespacios;
    private javax.swing.JTextArea Csilabas;
    private javax.swing.JTextField Cvocales;
    private javax.swing.JTextField Tfrase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables

}
